linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 3

linters:
  enable:
    - gofmt
    - govet
    - revive
    - gocyclo
    - goconst
    - ineffassign
    - misspell
    - unparam

run:
  timeout: 5m
